services:
  api:
    build: .
    container_name: hemogram-api
    environment:
      - DATABASE_URL=postgresql+psycopg2://hemouser:hemopass@postgres-db:5432/hemogram
      - APP_ENV=local
      - HASH_SALT=local-salt
      - TZ=America/Sao_Paulo
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14-alpine
    container_name: hemogram-postgres
    environment:
      - POSTGRES_USER=hemouser
      - POSTGRES_PASSWORD=hemopass
      - POSTGRES_DB=hemogram
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: