services:
  api:
    build: .
    container_name: hemogram-api
    environment:
      - DATABASE_URL=postgresql+psycopg2://hemouser:hemopass@postgres-db:5432/hemogram
      - REDIS_URL=redis://redis:6379/0
      - APP_ENV=local
      - HASH_SALT=local-salt
      - TZ=America/Sao_Paulo
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis

  postgres-db:
    image: postgres:14-alpine
    container_name: hemogram-postgres
    environment:
      - POSTGRES_USER=hemouser
      - POSTGRES_PASSWORD=hemopass
      - POSTGRES_DB=hemogram
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hemogram-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    environment:
      - TZ=America/Sao_Paulo

volumes:
  pgdata:
  redisdata: